name: Playwright tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  ui-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'adopt'

      - name: Setup Maven action
        uses: s4u/setup-maven-action@v1.7.0
        with:
          checkout-fetch-depth: 0
          java-version: 17
          java-distribution: temurin
          maven-version: 3.9.9

      - name: Install Playwright dependencies
        run: npx playwright install-deps

      - name: Install dependencies
        run: mvn clean install -DskipTests

      - name: Run Playwright tests
        run: mvn test

      - name: Archive trace files
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: traces
          path: target/traces/*.zip

      - name: Deploy cucumber report to Github pages
        if: always()
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          folder: ./target/cucumber-report